query GetDashboardData($bookingsInput: GetAppointmentsInput!, $nurseIdForStats: String!) {
  getBookings(input: $bookingsInput) {
    id
    startTime
    service {
      id
      name
    }
    person {
      id
      supabaseId
    }
  }
  getNurseStats(nurseId: $nurseIdForStats) {
    id
    totalRevenue
    rebookingsCount
    rebookingsRevenue
    newCustomersCount
    newCustomersRevenue
  }
} 