query GetNurseDataForBookingFlow($nurseId: String!) {
  getNurseById(id: $nurseId) {
    id
    timezone
    services {
      id
      name
      description
      price
      durationMinutes
      topPick
    }
    organization {
      id
      supabaseOrgId
    }
  }
}